version: '3.8'

services:
  frontend:
    build:
      context: ./HackMotion-GUI
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./HackMotion-API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=7200
    ports:
      - "7200:7200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
